modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/gloomybanana/dprm"
[[mods]]
modId="dprm"
version="${file.jarVersion}"
displayName="Datapack Recipe Maker"
displayURL="https://github.com/gloomybanana/dprm"
logoFile="dprm.png"
authors="gloomybanana"
description='''

'''