modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/gloomybanana/dprm"
[[mods]]
modId="dprm"
version="${file.jarVersion}"
displayName="Datapack Recipe Maker"
displayURL="https://github.com/gloomybanana/dprm"
logoFile="logo.png"
authors="gloomybanana"
description='''
this is an assistant tool designed for making vanilla datapack recipe.you can generate a vanilla recipe in you game world by drag item into craft table gui.
The .json files are saved in your saves directory
'''